fix: handleMessage parameter-from to fromNid
icon-project/xcall-multi pull request #28
Opened 2023-08-23 13:49 UTC by qwerty0789

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-08-28 09:52 UTC, AntonAndell requested changes
@sabinchitrakar @redlarva 
What do you think about this parameter. I personally think the naming makes sense enough. Since handleMessage is only used between connection and xCall which never deals with addresses at all but only network ids. So from can only the from network. 

But id be up to changing it. However it should be changed everywhere. 
Both xCall and connections in java and rust + spec

2023-09-06 03:54 UTC, redlarva commented
> @sabinchitrakar @redlarva What do you think about this parameter. I personally think the naming makes sense enough. Since handleMessage is only used between connection and xCall which never deals with addresses at all but only network ids. So from can only the from network.
> 
> But id be up to changing it. However it should be changed everywhere. Both xCall and connections in java and rust + spec

Indeed, it does make sense to make this change consistently across all contracts, including the specifications.

2023-09-12 10:16 UTC, AntonAndell requested changes

2023-09-12 10:16 UTC, AntonAndell commented on docs/adr/xcall.md
> +external function handleMessage(String fromNid, bytes _msg) {
Mabye keep the underscore here since all params in spec is with underscore

2023-09-15 04:43 UTC, AntonAndell approved these changes
LGTM

2023-09-15 04:45 UTC, merged