featt: rollback testcases
icon-project/xcall-multi pull request #92
Opened 2023-09-18 21:13 UTC by sdpisreddevil

## Description:

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2023-09-21 10:55 UTC, AntonAndell requested changes
Test cases look good, but need to be merged

2023-09-25 18:57 UTC, sdpisreddevil commented on contracts/evm/xcall/test/CallService.t.sol
> +        emit RollbackMessage(1);
updated

2023-09-26 04:47 UTC, AntonAndell requested changes

2023-09-26 04:47 UTC, AntonAndell commented on contracts/evm/xcall/test/CallService.t.sol
> +        emit RollbackMessage(1);
Also fix emit here

2023-09-26 04:47 UTC, AntonAndell commented on contracts/evm/xcall/test/CallService.t.sol
> +        emit RollbackMessage(1);
:point_up:

2023-09-26 04:47 UTC, AntonAndell commented on contracts/evm/xcall/test/CallService.t.sol
> +
:point_up:

2023-09-26 06:01 UTC, sdpisreddevil commented
@AntonAndell fixed

2023-09-26 06:02 UTC, AntonAndell approved these changes
Okey for now

2023-09-26 06:02 UTC, merged